/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAlimentacaoRouteImport } from './routes/_authenticated/alimentacao'
import { Route as AuthenticatedAmigoRouteImport } from './routes/_authenticated/amigo'
import { Route as AuthenticatedAssinaturaRouteImport } from './routes/_authenticated/assinatura'
import { Route as AuthenticatedCasalRouteImport } from './routes/_authenticated/casal'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedCompartilharRouteImport } from './routes/_authenticated/compartilhar'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated/compras'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDesafiosRouteImport } from './routes/_authenticated/desafios'
import { Route as AuthenticatedFotoRouteImport } from './routes/_authenticated/foto'
import { Route as AuthenticatedIndicacoesRouteImport } from './routes/_authenticated/indicacoes'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedTreinoRouteImport } from './routes/_authenticated/treino'
import { Route as CheckoutRetornoRouteImport } from './routes/checkout/retorno'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlimentacaoRoute =
  AuthenticatedAlimentacaoRouteImport.update({
    id: '/alimentacao',
    path: '/alimentacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmigoRoute = AuthenticatedAmigoRouteImport.update({
  id: '/amigo',
  path: '/amigo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssinaturaRoute = AuthenticatedAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCasalRoute = AuthenticatedCasalRouteImport.update({
  id: '/casal',
  path: '/casal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompartilharRoute =
  AuthenticatedCompartilharRouteImport.update({
    id: '/compartilhar',
    path: '/compartilhar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesafiosRoute = AuthenticatedDesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFotoRoute = AuthenticatedFotoRouteImport.update({
  id: '/foto',
  path: '/foto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIndicacoesRoute = AuthenticatedIndicacoesRouteImport.update({
  id: '/indicacoes',
  path: '/indicacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTreinoRoute = AuthenticatedTreinoRouteImport.update({
  id: '/treino',
  path: '/treino',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CheckoutRetornoRoute = CheckoutRetornoRouteImport.update({
  id: '/retorno',
  path: '/retorno',
  getParentRoute: () => CheckoutRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/alimentacao': typeof AuthenticatedAlimentacaoRoute
  '/amigo': typeof AuthenticatedAmigoRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/casal': typeof AuthenticatedCasalRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/compartilhar': typeof AuthenticatedCompartilharRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/desafios': typeof AuthenticatedDesafiosRoute
  '/foto': typeof AuthenticatedFotoRoute
  '/indicacoes': typeof AuthenticatedIndicacoesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/treino': typeof AuthenticatedTreinoRoute
  '/checkout/retorno': typeof CheckoutRetornoRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/alimentacao': typeof AuthenticatedAlimentacaoRoute
  '/amigo': typeof AuthenticatedAmigoRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/casal': typeof AuthenticatedCasalRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/compartilhar': typeof AuthenticatedCompartilharRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/desafios': typeof AuthenticatedDesafiosRoute
  '/foto': typeof AuthenticatedFotoRoute
  '/indicacoes': typeof AuthenticatedIndicacoesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/treino': typeof AuthenticatedTreinoRoute
  '/checkout/retorno': typeof CheckoutRetornoRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/alimentacao': typeof AuthenticatedAlimentacaoRoute
  '/_authenticated/amigo': typeof AuthenticatedAmigoRoute
  '/_authenticated/assinatura': typeof AuthenticatedAssinaturaRoute
  '/_authenticated/casal': typeof AuthenticatedCasalRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRoute
  '/_authenticated/compartilhar': typeof AuthenticatedCompartilharRoute
  '/_authenticated/compras': typeof AuthenticatedComprasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/desafios': typeof AuthenticatedDesafiosRoute
  '/_authenticated/foto': typeof AuthenticatedFotoRoute
  '/_authenticated/indicacoes': typeof AuthenticatedIndicacoesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/treino': typeof AuthenticatedTreinoRoute
  '/checkout/retorno': typeof CheckoutRetornoRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkout'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/admin'
    | '/alimentacao'
    | '/amigo'
    | '/assinatura'
    | '/casal'
    | '/coach'
    | '/compartilhar'
    | '/compras'
    | '/dashboard'
    | '/desafios'
    | '/foto'
    | '/indicacoes'
    | '/onboarding'
    | '/perfil'
    | '/treino'
    | '/checkout/retorno'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkout'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/admin'
    | '/alimentacao'
    | '/amigo'
    | '/assinatura'
    | '/casal'
    | '/coach'
    | '/compartilhar'
    | '/compras'
    | '/dashboard'
    | '/desafios'
    | '/foto'
    | '/indicacoes'
    | '/onboarding'
    | '/perfil'
    | '/treino'
    | '/checkout/retorno'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/checkout'
    | '/privacidade'
    | '/sitemap.xml'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/alimentacao'
    | '/_authenticated/amigo'
    | '/_authenticated/assinatura'
    | '/_authenticated/casal'
    | '/_authenticated/coach'
    | '/_authenticated/compartilhar'
    | '/_authenticated/compras'
    | '/_authenticated/dashboard'
    | '/_authenticated/desafios'
    | '/_authenticated/foto'
    | '/_authenticated/indicacoes'
    | '/_authenticated/onboarding'
    | '/_authenticated/perfil'
    | '/_authenticated/treino'
    | '/checkout/retorno'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alimentacao': {
      id: '/_authenticated/alimentacao'
      path: '/alimentacao'
      fullPath: '/alimentacao'
      preLoaderRoute: typeof AuthenticatedAlimentacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/amigo': {
      id: '/_authenticated/amigo'
      path: '/amigo'
      fullPath: '/amigo'
      preLoaderRoute: typeof AuthenticatedAmigoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assinatura': {
      id: '/_authenticated/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AuthenticatedAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/casal': {
      id: '/_authenticated/casal'
      path: '/casal'
      fullPath: '/casal'
      preLoaderRoute: typeof AuthenticatedCasalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compartilhar': {
      id: '/_authenticated/compartilhar'
      path: '/compartilhar'
      fullPath: '/compartilhar'
      preLoaderRoute: typeof AuthenticatedCompartilharRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras': {
      id: '/_authenticated/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desafios': {
      id: '/_authenticated/desafios'
      path: '/desafios'
      fullPath: '/desafios'
      preLoaderRoute: typeof AuthenticatedDesafiosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/foto': {
      id: '/_authenticated/foto'
      path: '/foto'
      fullPath: '/foto'
      preLoaderRoute: typeof AuthenticatedFotoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicacoes': {
      id: '/_authenticated/indicacoes'
      path: '/indicacoes'
      fullPath: '/indicacoes'
      preLoaderRoute: typeof AuthenticatedIndicacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treino': {
      id: '/_authenticated/treino'
      path: '/treino'
      fullPath: '/treino'
      preLoaderRoute: typeof AuthenticatedTreinoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/checkout/retorno': {
      id: '/checkout/retorno'
      path: '/retorno'
      fullPath: '/checkout/retorno'
      preLoaderRoute: typeof CheckoutRetornoRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAlimentacaoRoute: typeof AuthenticatedAlimentacaoRoute
  AuthenticatedAmigoRoute: typeof AuthenticatedAmigoRoute
  AuthenticatedAssinaturaRoute: typeof AuthenticatedAssinaturaRoute
  AuthenticatedCasalRoute: typeof AuthenticatedCasalRoute
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRoute
  AuthenticatedCompartilharRoute: typeof AuthenticatedCompartilharRoute
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDesafiosRoute: typeof AuthenticatedDesafiosRoute
  AuthenticatedFotoRoute: typeof AuthenticatedFotoRoute
  AuthenticatedIndicacoesRoute: typeof AuthenticatedIndicacoesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedTreinoRoute: typeof AuthenticatedTreinoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAlimentacaoRoute: AuthenticatedAlimentacaoRoute,
  AuthenticatedAmigoRoute: AuthenticatedAmigoRoute,
  AuthenticatedAssinaturaRoute: AuthenticatedAssinaturaRoute,
  AuthenticatedCasalRoute: AuthenticatedCasalRoute,
  AuthenticatedCoachRoute: AuthenticatedCoachRoute,
  AuthenticatedCompartilharRoute: AuthenticatedCompartilharRoute,
  AuthenticatedComprasRoute: AuthenticatedComprasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDesafiosRoute: AuthenticatedDesafiosRoute,
  AuthenticatedFotoRoute: AuthenticatedFotoRoute,
  AuthenticatedIndicacoesRoute: AuthenticatedIndicacoesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedTreinoRoute: AuthenticatedTreinoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CheckoutRouteChildren {
  CheckoutRetornoRoute: typeof CheckoutRetornoRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutRetornoRoute: CheckoutRetornoRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
